Server/Controllers/FranchisesController.cs
using Microsoft.AspNetCore.Mvc;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Authorization;
using KSU.CS.Pendant.Server.Models;

namespace KSU.CS.Pendant.Server.Controllers
{
    /// <summary>
    /// A controller for creating, viewing, updating, and deleting franchises
    /// used for the CIS 400 semester-long project
    /// </summary>
    public class FranchisesController : Controller
    {
        private readonly DataContext _context;

        /// <summary>
        /// Constructs a new CourseController using dependency injection
        /// </summary>
        /// <param name="context">The site database context</param>
        public FranchisesController(DataContext context)
        {
            _context = context;
        }

        #region Route Methods

        /// <summary>
        /// Lists the available franchises
        /// </summary>
        /// <returns>A HTML page listing the franchises</returns>
        public async Task<IActionResult> Index()
        {
            var user = await _context.Users
                .Include(u => u.FranchiseLocation)
                .ThenInclude(l => l.OrderRecords)
                .Where(u => u.ID == int.Parse(User.FindFirst("ID").Value))
                .FirstAsync();

//            if (user.IsAdmin || user.IsFaculty)
//            {
//                var franchises = await _context.FranchiseLocations.ToListAsync();
//                return View(franchises);
//            }
//            else
            {
                // Create the Franchise Location for this user if it
                // does not yet exist
                if (user.FranchiseLocation is null)
                {
                    user.FranchiseLocation = new FranchiseLocation()
                    {
                        Name = $"{user.FullName}'s Franchise"
                    };
                    _context.Update(user);
                    await _context.SaveChangesAsync();
                }
                return View("Details", user.FranchiseLocation);
            }
        }

        /// <summary>
        /// A page giving details of the selected franchise with <paramref name="id"/>
        /// </summary>
        /// <param name="id">The franchise database ID</param>
        /// <returns>A HTML page with the details</returns>
        public async Task<IActionResult> Details(int id)
        {
            var franchise = await _context.FranchiseLocations
                .Where(f => f.ID == id)
                .FirstOrDefaultAsync();

            if (franchise is null) return NotFound();

            return View(franchise);
        }
        public async Task<IActionResult> Update(FranchiseLocation franchise)
        {
            if (!ModelState.IsValid)
            {
                return View();
            }

            // Save the Franchise
            _context.FranchiseLocations.Update(franchise);
            await _context.SaveChangesAsync();

            return RedirectToAction("Details", new { ID = franchise.ID });
        }

        /// <summary>
        /// Regenerates the user's secret to use with the GitHub Webhooks
        /// </summary>
        /// <returns>A HTTP redirect</returns>
        [Route("RegenerateSecret")]
        public async Task<IActionResult> RegenerateSecret()
        {
            // Load the current user's data
            User user = await _context.Users
                .Include(u => u.FranchiseLocation)
                .FirstAsync(i => i.ID == int.Parse(User.FindFirst("ID").Value));

            // The user must have a connected franchise location
            if (user.FranchiseLocation == null) return NotFound();

            // Regenerate the user's secret 
            user.FranchiseLocation.GenerateSecret();

            // Save the change 
            _context.Update(user.FranchiseLocation);
            await _context.SaveChangesAsync();

            return RedirectToAction("Details", new { ID = user.FranchiseLocation.ID });
        }

        #endregion
    }
}

Server/Views/Franchises/Create.cshtml
@model KSU.CS.Pendant.Server.Models.FranchiseLocation

@{
    ViewData["Title"] = "Create";
}

<h1>Create a Franchise Location</h1>

<div class="row">
    <div class="col-md-12">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

Server/Views/Franchises/Details.cshtml
@model KSU.CS.Pendant.Server.Models.FranchiseLocation

@{ ViewData["Title"] = "Franchise Details"; }

<h1>@Model.Name</h1>
<hr />
<h3>Franchise Secret</h3>
<p>
    Your secret is:
    <input id="secret" type="password" value="@Model.Secret" class="col-lg-4" />
    <button id="toggle-secret" class="btn btn-primary" role="button" aria-expanded="false" aria-controls="secret">Show</button>
    <a asp-controller="Franchises" asp-action="RegenerateSecret" class="btn btn-danger">Regenerate Secret</a>
</p>
<p>
    You can sumbit orders to this API using a HTTP POST request with the url:
    <code>https://pendant.cs.ksu.edu/franchise/@Model.ID/orders</code>
    including the above secret in the <code>Authorization</code> header.
</p>
<h3>Franchise Order History</h3>
@if(Model.OrderRecords.Count == 0)
{
    <p>No orders have been recieved yet</p>
}
else foreach(var order in Model.OrderRecords)
{
    <div>
        <h5>Order #@order.Number</h5>
        <dl>
            <dt>Placed At</dt>
            <dd>@order.DateTime</dd>
            <dt>Subtotal</dt>
            <dd>@order.Subtotal</dd>
            <dt>Tax</dt>
            <dd>@order.Tax</dd>
            <dt>Total</dt>
            <dd>@order.Total</dd>
            <dt>Items</dt>
            <dd>@order.Items</dd>
        </dl>
    </div>
}

@section Scripts
{
    <script>// Toggles the visibility of the secret
        $('#toggle-secret').on('click', function () {
            var button = $('#toggle-secret');
            var input = $("#secret");
            if (input.attr('type') == 'password') {
                input.attr('type', 'text');
                button.text("Hide");
            } else {
                input.attr('type', 'password');
                button.text("Show");
            }
        });</script>
}

Server/Views/Franchises/Edit.cshtml
@model KSU.CS.Pendant.Server.Models.FranchiseLocation

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit Franchise</h1>
<hr />
<div class="row">
    <div class="col-md-12">
        <form asp-action="Update">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="ID" />
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>  
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

Server/Views/Franchises/Index.cshtml
@model IEnumerable<KSU.CS.Pendant.Server.Models.FranchiseLocation>

@{
    ViewData["Title"] = "Franchise List";
}

<h1>Courses</h1>
<p>@Html.ActionLink("Create new", "Create")</p>
<table class="table">
    <tr>
        <th>@Html.DisplayNameFor(model => model.Name)</th>
        <th></th>
    </tr>
    @foreach (var item in Model)
    {
        <tr>
            <td>@Html.DisplayFor(modelItem => item.Name)</td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.ID">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.ID">Details</a>
            </td>
        </tr>
    }

</table>